name: hamo_service_man
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  font_awesome_flutter: 10.5.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - packages/intl_phone_field/assets/flags/
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
